/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [1.44MB] > C:\Stiven\allaboutikan\happynewyearleti new\happynewyear-leti\public\models\butterfly\dragon\scene-transformed.glb [5.27MB] (-265%)
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-koi-b6c5d2efb986489a96318a31b3f1a348
Title: Dragon Koi
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dragon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/dragon/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Object_0.timeScale = 0.15
    actions.Object_0.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Sphere002_0" position={[0.002, 0.2, -2]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
          </group>
          <group name="Circle_1" />
          <group name="Circle001_2" position={[0.002, 0.2, -2]} />
          <group name="Sphere003_3" position={[0.176, 0.198, -1.992]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} />
          </group>
          <group name="Circle003_4" />
          <group name="Circle004_5" position={[0.176, 0.198, -1.992]} rotation={[Math.PI / 9, 0, 0]} />
          <group name="Sphere004_6" position={[0.349, 0.196, -1.97]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material} />
          </group>
          <group name="Circle006_7" />
          <group name="Circle007_8" position={[0.349, 0.196, -1.97]} rotation={[0.698, 0, 0]} />
          <group name="Sphere005_9" position={[0.52, 0.194, -1.932]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material} />
          </group>
          <group name="Circle009_10" />
          <group name="Circle010_11" position={[0.52, 0.194, -1.932]} rotation={[Math.PI / 3, 0, 0]} />
          <group name="Sphere006_12" position={[0.686, 0.192, -1.879]}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material} />
          </group>
          <group name="Circle012_13" />
          <group name="Circle013_14" position={[0.686, 0.192, -1.879]} rotation={[1.396, 0, 0]} />
          <group name="Sphere007_15" position={[0.847, 0.191, -1.813]} scale={0.918}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material} />
          </group>
          <group name="Circle015_16" />
          <group name="Circle016_17" position={[0.847, 0.191, -1.813]} rotation={[1.745, 0, 0]} scale={0.918} />
          <group name="Sphere008_18" position={[1.002, 0.189, -1.732]} scale={0.825}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material} />
          </group>
          <group name="Circle018_19" />
          <group name="Circle019_20" position={[1.002, 0.189, -1.732]} rotation={[2.094, 0, 0]} />
          <group name="Sphere009_21" position={[1.149, 0.187, -1.638]} scale={0.775}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material} />
          </group>
          <group name="Circle021_22" />
          <group name="Circle022_23" position={[1.149, 0.187, -1.638]} rotation={[2.443, 0, 0]} scale={1.073} />
          <group name="Sphere010_24" position={[1.288, 0.186, -1.532]} scale={0.73}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material} />
          </group>
          <group name="Circle024_25" />
          <group name="Circle025_26" position={[1.288, 0.186, -1.532]} rotation={[2.793, 0, 0]} scale={1.075} />
          <group name="Sphere011_27" position={[1.416, 0.185, -1.414]} scale={0.69}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material} />
          </group>
          <group name="Circle027_28" />
          <group name="Circle028_29" position={[1.416, 0.185, -1.414]} rotation={[-2.793, 0, 0]} scale={1.018} />
          <group name="Sphere012_30" position={[1.534, 0.183, -1.286]} scale={0.696}>
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material} />
          </group>
          <group name="Circle030_31" />
          <group name="Circle031_32" position={[1.534, 0.183, -1.286]} rotation={[-2.443, 0, 0]} scale={0.998} />
          <group name="Sphere013_33" position={[1.64, 0.182, -1.147]} scale={0.629}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material} />
          </group>
          <group name="Circle033_34" />
          <group name="Circle034_35" position={[1.64, 0.182, -1.147]} rotation={[-2.094, 0, 0]} scale={0.879} />
          <group name="Sphere014_36" position={[1.734, 0.181, -1]} scale={0.603}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material} />
          </group>
          <group name="Circle036_37" />
          <group name="Circle037_38" position={[1.734, 0.181, -1]} rotation={[-1.745, 0, 0]} scale={0.832} />
          <group name="Sphere015_39" position={[1.815, 0.18, -0.845]} scale={0.546}>
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material} />
          </group>
          <group name="Circle039_40" />
          <group name="Circle040_41" position={[1.815, 0.18, -0.845]} rotation={[-1.396, 0, 0]} scale={0.76} />
          <group name="Sphere016_42" position={[1.881, 0.18, -0.684]} scale={0.502}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material} />
          </group>
          <group name="Circle042_43" />
          <group name="Circle043_44" position={[1.881, 0.18, -0.684]} rotation={[-Math.PI / 3, 0, 0]} scale={0.714} />
          <group name="Sphere017_45" position={[1.934, 0.179, -0.518]} scale={0.468}>
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material} />
          </group>
          <group name="Circle045_46" />
          <group name="Circle046_47" position={[1.934, 0.179, -0.518]} rotation={[-0.698, 0, 0]} scale={0.685} />
          <group name="Sphere018_48" position={[1.972, 0.179, -0.347]} scale={0.447}>
            <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material} />
          </group>
          <group name="Circle048_49" />
          <group name="Circle049_50" position={[1.972, 0.179, -0.347]} rotation={[-Math.PI / 9, 0, 0]} scale={0.668} />
          <group name="Sphere019_51" position={[1.994, 0.178, -0.174]} scale={0.44}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material} />
          </group>
          <group name="Circle051_52" />
          <group name="Circle052_53" position={[1.994, 0.178, -0.174]} scale={0.663} />
          <group name="Sphere001_54" position={[-1.748, 0.916, 0.459]}>
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material} />
          </group>
          <group name="Circle055_55" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle056_56" position={[-1.748, 0.916, 0.459]} />
          <group name="Sphere020_57" position={[-1.807, 0.76, 0.513]}>
            <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material} />
          </group>
          <group name="Circle058_58" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle059_59" position={[-1.807, 0.76, 0.513]} rotation={[Math.PI / 9, 0, 0]} />
          <group name="Sphere021_60" position={[-1.853, 0.599, 0.563]}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material} />
          </group>
          <group name="Circle061_61" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle062_62" position={[-1.853, 0.599, 0.563]} rotation={[0.698, 0, 0]} />
          <group name="Sphere022_63" position={[-1.885, 0.434, 0.606]}>
            <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material} />
          </group>
          <group name="Circle064_64" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle065_65" position={[-1.885, 0.434, 0.606]} rotation={[Math.PI / 3, 0, 0]} />
          <group name="Sphere023_66" position={[-1.904, 0.264, 0.644]}>
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material} />
          </group>
          <group name="Circle067_67" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle068_68" position={[-1.904, 0.264, 0.644]} rotation={[1.396, 0, 0]} />
          <group name="Sphere024_69" position={[-1.909, 0.093, 0.675]} scale={0.918}>
            <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material} />
          </group>
          <group name="Circle070_70" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle071_71" position={[-1.909, 0.093, 0.675]} rotation={[1.745, 0, 0]} scale={0.918} />
          <group name="Sphere025_72" position={[-1.901, -0.08, 0.701]} scale={0.825}>
            <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material} />
          </group>
          <group name="Circle073_73" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle074_74" position={[-1.901, -0.08, 0.701]} rotation={[2.094, 0, 0]} />
          <group name="Sphere026_75" position={[-1.878, -0.252, 0.719]} scale={0.775}>
            <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material} />
          </group>
          <group name="Circle076_76" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle077_77" position={[-1.878, -0.252, 0.719]} rotation={[2.443, 0, 0]} scale={1.073} />
          <group name="Sphere027_78" position={[-1.842, -0.422, 0.731]} scale={0.73}>
            <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material} />
          </group>
          <group name="Circle079_79" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle080_80" position={[-1.842, -0.422, 0.731]} rotation={[2.793, 0, 0]} scale={1.075} />
          <group name="Sphere028_81" position={[-1.793, -0.589, 0.736]} scale={0.69}>
            <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material} />
          </group>
          <group name="Circle082_82" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle083_83" position={[-1.793, -0.589, 0.736]} rotation={[-2.793, 0, 0]} scale={1.018} />
          <group name="Sphere029_84" position={[-1.731, -0.752, 0.734]} scale={0.696}>
            <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material} />
          </group>
          <group name="Circle085_85" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle086_86" position={[-1.731, -0.752, 0.734]} rotation={[-2.443, 0, 0]} scale={0.998} />
          <group name="Sphere030_87" position={[-1.657, -0.91, 0.726]} scale={0.629}>
            <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material} />
          </group>
          <group name="Circle088_88" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle089_89" position={[-1.657, -0.91, 0.726]} rotation={[-2.094, 0, 0]} scale={0.879} />
          <group name="Sphere031_90" position={[-1.57, -1.061, 0.71]} scale={0.603}>
            <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material} />
          </group>
          <group name="Circle091_91" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle092_92" position={[-1.57, -1.061, 0.71]} rotation={[-1.745, 0, 0]} scale={0.832} />
          <group name="Sphere032_93" position={[-1.473, -1.204, 0.688]} scale={0.546}>
            <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material} />
          </group>
          <group name="Circle094_94" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle095_95" position={[-1.473, -1.204, 0.688]} rotation={[-1.396, 0, 0]} scale={0.76} />
          <group name="Sphere033_96" position={[-1.365, -1.338, 0.66]} scale={0.502}>
            <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material} />
          </group>
          <group name="Circle097_97" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle098_98" position={[-1.365, -1.338, 0.66]} rotation={[-Math.PI / 3, 0, 0]} scale={0.714} />
          <group name="Sphere034_99" position={[-1.247, -1.462, 0.625]} scale={0.468}>
            <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material} />
          </group>
          <group name="Circle100_100" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle101_101" position={[-1.247, -1.462, 0.625]} rotation={[-0.698, 0, 0]} scale={0.685} />
          <group name="Sphere035_102" position={[-1.12, -1.575, 0.584]} scale={0.447}>
            <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material} />
          </group>
          <group name="Circle103_103" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle104_104" position={[-1.12, -1.575, 0.584]} rotation={[-Math.PI / 9, 0, 0]} scale={0.668} />
          <group name="Sphere036_105" position={[-0.986, -1.676, 0.538]} scale={0.44}>
            <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.material} />
          </group>
          <group name="Circle106_106" position={[-0.013, 0.003, 0.015]} />
          <group name="Circle107_107" position={[-0.986, -1.676, 0.538]} scale={0.663} />
          <group name="Sphere037_108" position={[0.776, 0.749, 1.705]}>
            <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.material} />
          </group>
          <group name="Circle110_109" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle111_110" position={[0.776, 0.749, 1.705]} />
          <group name="Sphere038_111" position={[0.807, 0.897, 1.618]}>
            <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.material} />
          </group>
          <group name="Circle113_112" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle114_113" position={[0.807, 0.897, 1.618]} rotation={[Math.PI / 9, 0, 0]} />
          <group name="Sphere039_114" position={[0.833, 1.038, 1.519]}>
            <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material} />
          </group>
          <group name="Circle116_115" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle117_116" position={[0.833, 1.038, 1.519]} rotation={[0.698, 0, 0]} />
          <group name="Sphere040_117" position={[0.854, 1.171, 1.407]}>
            <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.material} />
          </group>
          <group name="Circle119_118" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle120_119" position={[0.854, 1.171, 1.407]} rotation={[Math.PI / 3, 0, 0]} />
          <group name="Sphere041_120" position={[0.87, 1.294, 1.285]}>
            <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material} />
          </group>
          <group name="Circle122_121" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle123_122" position={[0.87, 1.294, 1.285]} rotation={[1.396, 0, 0]} />
          <group name="Sphere042_123" position={[0.881, 1.407, 1.153]} scale={0.918}>
            <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.material} />
          </group>
          <group name="Circle125_124" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle126_125" position={[0.881, 1.407, 1.153]} rotation={[1.745, 0, 0]} scale={0.918} />
          <group name="Sphere043_126" position={[0.886, 1.51, 1.012]} scale={0.825}>
            <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.material} />
          </group>
          <group name="Circle128_127" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle129_128" position={[0.886, 1.51, 1.012]} rotation={[2.094, 0, 0]} />
          <group name="Sphere044_129" position={[0.886, 1.6, 0.862]} scale={0.775}>
            <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material} />
          </group>
          <group name="Circle131_130" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle132_131" position={[0.886, 1.6, 0.862]} rotation={[2.443, 0, 0]} scale={1.073} />
          <group name="Sphere045_132" position={[0.88, 1.678, 0.706]} scale={0.73}>
            <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.material} />
          </group>
          <group name="Circle134_133" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle135_134" position={[0.88, 1.678, 0.706]} rotation={[2.793, 0, 0]} scale={1.075} />
          <group name="Sphere046_135" position={[0.869, 1.743, 0.545]} scale={0.69}>
            <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.material} />
          </group>
          <group name="Circle137_136" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle138_137" position={[0.869, 1.743, 0.545]} rotation={[-2.793, 0, 0]} scale={1.018} />
          <group name="Sphere047_138" position={[0.853, 1.794, 0.379]} scale={0.696}>
            <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.material} />
          </group>
          <group name="Circle140_139" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle141_140" position={[0.853, 1.794, 0.379]} rotation={[-2.443, 0, 0]} scale={0.998} />
          <group name="Sphere048_141" position={[0.831, 1.832, 0.21]} scale={0.629}>
            <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.material} />
          </group>
          <group name="Circle143_142" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle144_143" position={[0.831, 1.832, 0.21]} rotation={[-2.094, 0, 0]} scale={0.879} />
          <group name="Sphere049_144" position={[0.805, 1.855, 0.039]} scale={0.603}>
            <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.material} />
          </group>
          <group name="Circle146_145" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle147_146" position={[0.805, 1.855, 0.039]} rotation={[-1.745, 0, 0]} scale={0.832} />
          <group name="Sphere050_147" position={[0.774, 1.863, -0.133]} scale={0.546}>
            <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.material} />
          </group>
          <group name="Circle149_148" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle150_149" position={[0.774, 1.863, -0.133]} rotation={[-1.396, 0, 0]} scale={0.76} />
          <group name="Sphere051_150" position={[0.738, 1.857, -0.303]} scale={0.502}>
            <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.material} />
          </group>
          <group name="Circle152_151" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle153_152" position={[0.738, 1.857, -0.303]} rotation={[-Math.PI / 3, 0, 0]} scale={0.714} />
          <group name="Sphere052_153" position={[0.698, 1.837, -0.472]} scale={0.468}>
            <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.material} />
          </group>
          <group name="Circle155_154" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle156_155" position={[0.698, 1.837, -0.472]} rotation={[-0.698, 0, 0]} scale={0.685} />
          <group name="Sphere053_156" position={[0.654, 1.802, -0.637]} scale={0.447}>
            <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material} />
          </group>
          <group name="Circle158_157" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle159_158" position={[0.654, 1.802, -0.637]} rotation={[-Math.PI / 9, 0, 0]} scale={0.668} />
          <group name="Sphere054_159" position={[0.606, 1.754, -0.798]} scale={0.44}>
            <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.material} />
          </group>
          <group name="Circle161_160" position={[-0.012, 0.018, 0.007]} />
          <group name="Circle162_161" position={[0.606, 1.754, -0.798]} scale={0.663} />
          <group name="Sphere055_162" position={[1.235, -1.52, 0.429]}>
            <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.material} />
          </group>
          <group name="Circle165_163" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle166_164" position={[1.235, -1.52, 0.429]} />
          <group name="Sphere056_165" position={[1.22, -1.477, 0.597]}>
            <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material} />
          </group>
          <group name="Circle168_166" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle169_167" position={[1.22, -1.477, 0.597]} rotation={[Math.PI / 9, 0, 0]} />
          <group name="Sphere057_168" position={[1.196, -1.422, 0.761]}>
            <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.material} />
          </group>
          <group name="Circle171_169" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle172_170" position={[1.196, -1.422, 0.761]} rotation={[0.698, 0, 0]} />
          <group name="Sphere058_171" position={[1.165, -1.355, 0.919]}>
            <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.material} />
          </group>
          <group name="Circle174_172" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle175_173" position={[1.165, -1.355, 0.919]} rotation={[Math.PI / 3, 0, 0]} />
          <group name="Sphere059_174" position={[1.125, -1.277, 1.07]}>
            <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.material} />
          </group>
          <group name="Circle177_175" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle178_176" position={[1.125, -1.277, 1.07]} rotation={[1.396, 0, 0]} />
          <group name="Sphere060_177" position={[1.079, -1.188, 1.213]} scale={0.918}>
            <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.material} />
          </group>
          <group name="Circle180_178" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle181_179" position={[1.079, -1.188, 1.213]} rotation={[1.745, 0, 0]} scale={0.918} />
          <group name="Sphere061_180" position={[1.025, -1.09, 1.347]} scale={0.825}>
            <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.material} />
          </group>
          <group name="Circle183_181" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle184_182" position={[1.025, -1.09, 1.347]} rotation={[2.094, 0, 0]} />
          <group name="Sphere062_183" position={[0.965, -0.982, 1.47]} scale={0.775}>
            <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.material} />
          </group>
          <group name="Circle186_184" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle187_185" position={[0.965, -0.982, 1.47]} rotation={[2.443, 0, 0]} scale={1.073} />
          <group name="Sphere063_186" position={[0.899, -0.866, 1.582]} scale={0.73}>
            <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.material} />
          </group>
          <group name="Circle189_187" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle190_188" position={[0.899, -0.866, 1.582]} rotation={[2.793, 0, 0]} scale={1.075} />
          <group name="Sphere064_189" position={[0.827, -0.743, 1.683]} scale={0.69}>
            <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.material} />
          </group>
          <group name="Circle192_190" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle193_191" position={[0.827, -0.743, 1.683]} rotation={[-2.793, 0, 0]} scale={1.018} />
          <group name="Sphere065_192" position={[0.75, -0.613, 1.77]} scale={0.696}>
            <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.material} />
          </group>
          <group name="Circle195_193" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle196_194" position={[0.75, -0.613, 1.77]} rotation={[-2.443, 0, 0]} scale={0.998} />
          <group name="Sphere066_195" position={[0.668, -0.478, 1.844]} scale={0.629}>
            <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.material} />
          </group>
          <group name="Circle198_196" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle199_197" position={[0.668, -0.478, 1.844]} rotation={[-2.094, 0, 0]} scale={0.879} />
          <group name="Sphere067_198" position={[0.583, -0.338, 1.904]} scale={0.603}>
            <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.material} />
          </group>
          <group name="Circle201_199" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle202_200" position={[0.583, -0.338, 1.904]} rotation={[-1.745, 0, 0]} scale={0.832} />
          <group name="Sphere068_201" position={[0.494, -0.195, 1.95]} scale={0.546}>
            <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.material} />
          </group>
          <group name="Circle204_202" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle205_203" position={[0.494, -0.195, 1.95]} rotation={[-1.396, 0, 0]} scale={0.76} />
          <group name="Sphere069_204" position={[0.403, -0.049, 1.981]} scale={0.502}>
            <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.material} />
          </group>
          <group name="Circle207_205" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle208_206" position={[0.403, -0.049, 1.981]} rotation={[-Math.PI / 3, 0, 0]} scale={0.714} />
          <group name="Sphere070_207" position={[0.31, 0.097, 1.996]} scale={0.468}>
            <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.material} />
          </group>
          <group name="Circle210_208" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle211_209" position={[0.31, 0.097, 1.996]} rotation={[-0.698, 0, 0]} scale={0.685} />
          <group name="Sphere071_210" position={[0.215, 0.244, 1.997]} scale={0.447}>
            <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.material} />
          </group>
          <group name="Circle213_211" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle214_212" position={[0.215, 0.244, 1.997]} rotation={[-Math.PI / 9, 0, 0]} scale={0.668} />
          <group name="Sphere072_213" position={[0.121, 0.39, 1.982]} scale={0.44}>
            <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.material} />
          </group>
          <group name="Circle216_214" position={[-0.012, 0.001, 0.015]} />
          <group name="Circle217_215" position={[0.121, 0.39, 1.982]} scale={0.663} />
          <group name="Sphere073_294" position={[-0.708, 1.201, -0.264]} scale={0.7}>
            <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.material} />
          </group>
          <group name="Circle222_295" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle223_296" position={[-0.708, 1.201, -0.264]} scale={0.7} />
          <group name="Sphere074_297" position={[-0.6, 1.259, -0.261]} scale={0.7}>
            <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.material} />
          </group>
          <group name="Circle225_298" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle226_299" position={[-0.6, 1.259, -0.261]} rotation={[Math.PI / 9, 0, 0]} scale={0.7} />
          <group name="Sphere075_300" position={[-0.488, 1.308, -0.255]} scale={0.7}>
            <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.material} />
          </group>
          <group name="Circle228_301" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle229_302" position={[-0.488, 1.308, -0.255]} rotation={[0.698, 0, 0]} scale={0.7} />
          <group name="Sphere076_303" position={[-0.373, 1.347, -0.246]} scale={0.7}>
            <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.material} />
          </group>
          <group name="Circle231_304" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle232_305" position={[-0.373, 1.347, -0.246]} rotation={[Math.PI / 3, 0, 0]} scale={0.7} />
          <group name="Sphere077_306" position={[-0.255, 1.376, -0.234]} scale={0.7}>
            <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.material} />
          </group>
          <group name="Circle234_307" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle235_308" position={[-0.255, 1.376, -0.234]} rotation={[1.396, 0, 0]} scale={0.7} />
          <group name="Sphere078_309" position={[-0.135, 1.395, -0.22]} scale={0.643}>
            <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials.material} />
          </group>
          <group name="Circle237_310" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle238_311" position={[-0.135, 1.395, -0.22]} rotation={[1.745, 0, 0]} scale={0.643} />
          <group name="Sphere079_312" position={[-0.015, 1.404, -0.202]} scale={0.578}>
            <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials.material} />
          </group>
          <group name="Circle240_313" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle241_314" position={[-0.015, 1.404, -0.202]} rotation={[2.094, 0, 0]} scale={0.7} />
          <group name="Sphere080_315" position={[0.106, 1.403, -0.182]} scale={0.542}>
            <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials.material} />
          </group>
          <group name="Circle243_316" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle244_317" position={[0.106, 1.403, -0.182]} rotation={[2.443, 0, 0]} scale={0.751} />
          <group name="Sphere081_318" position={[0.225, 1.391, -0.16]} scale={0.511}>
            <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials.material} />
          </group>
          <group name="Circle246_319" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle247_320" position={[0.225, 1.391, -0.16]} rotation={[2.793, 0, 0]} scale={0.752} />
          <group name="Sphere082_321" position={[0.343, 1.368, -0.136]} scale={0.483}>
            <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials.material} />
          </group>
          <group name="Circle249_322" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle250_323" position={[0.343, 1.368, -0.136]} rotation={[-2.793, 0, 0]} scale={0.713} />
          <group name="Sphere083_324" position={[0.458, 1.336, -0.109]} scale={0.487}>
            <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials.material} />
          </group>
          <group name="Circle252_325" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle253_326" position={[0.458, 1.336, -0.109]} rotation={[-2.443, 0, 0]} scale={0.699} />
          <group name="Sphere084_327" position={[0.569, 1.294, -0.081]} scale={0.44}>
            <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials.material} />
          </group>
          <group name="Circle255_328" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle256_329" position={[0.569, 1.294, -0.081]} rotation={[-2.094, 0, 0]} scale={0.615} />
          <group name="Sphere085_330" position={[0.675, 1.243, -0.05]} scale={0.422}>
            <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials.material} />
          </group>
          <group name="Circle258_331" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle259_332" position={[0.675, 1.243, -0.05]} rotation={[-1.745, 0, 0]} scale={0.583} />
          <group name="Sphere086_333" position={[0.776, 1.182, -0.019]} scale={0.382}>
            <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials.material} />
          </group>
          <group name="Circle261_334" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle262_335" position={[0.776, 1.182, -0.019]} rotation={[-1.396, 0, 0]} scale={0.532} />
          <group name="Sphere087_336" position={[0.872, 1.113, 0.014]} scale={0.351}>
            <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials.material} />
          </group>
          <group name="Circle264_337" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle265_338" position={[0.872, 1.113, 0.014]} rotation={[-Math.PI / 3, 0, 0]} scale={0.5} />
          <group name="Sphere088_339" position={[0.96, 1.035, 0.047]} scale={0.328}>
            <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials.material} />
          </group>
          <group name="Circle267_340" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle268_341" position={[0.96, 1.035, 0.047]} rotation={[-0.698, 0, 0]} scale={0.48} />
          <group name="Sphere089_342" position={[1.041, 0.95, 0.081]} scale={0.313}>
            <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.material} />
          </group>
          <group name="Circle270_343" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle271_344" position={[1.041, 0.95, 0.081]} rotation={[-Math.PI / 9, 0, 0]} scale={0.468} />
          <group name="Sphere090_345" position={[1.113, 0.858, 0.116]} scale={0.308}>
            <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.material} />
          </group>
          <group name="Circle273_346" position={[-0.004, 0.012, -0.001]} scale={0.7} />
          <group name="Circle274_347" position={[1.113, 0.858, 0.116]} scale={0.464} />
          <group name="Sphere091_348" position={[-1.003, -0.733, 0.678]} scale={0.7}>
            <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials.material} />
          </group>
          <group name="Circle277_349" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle278_350" position={[-1.003, -0.733, 0.678]} scale={0.7} />
          <group name="Sphere092_351" position={[-1.002, -0.811, 0.583]} scale={0.7}>
            <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.material} />
          </group>
          <group name="Circle280_352" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle281_353" position={[-1.002, -0.811, 0.583]} rotation={[Math.PI / 9, 0, 0]} scale={0.7} />
          <group name="Sphere093_354" position={[-0.994, -0.882, 0.484]} scale={0.7}>
            <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials.material} />
          </group>
          <group name="Circle283_355" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle284_356" position={[-0.994, -0.882, 0.484]} rotation={[0.698, 0, 0]} scale={0.7} />
          <group name="Sphere094_357" position={[-0.979, -0.946, 0.381]} scale={0.7}>
            <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials.material} />
          </group>
          <group name="Circle286_358" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle287_359" position={[-0.979, -0.946, 0.381]} rotation={[Math.PI / 3, 0, 0]} scale={0.7} />
          <group name="Sphere095_360" position={[-0.959, -1.002, 0.275]} scale={0.7}>
            <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.material} />
          </group>
          <group name="Circle289_361" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle290_362" position={[-0.959, -1.002, 0.275]} rotation={[1.396, 0, 0]} scale={0.7} />
          <group name="Sphere096_363" position={[-0.931, -1.05, 0.166]} scale={0.643}>
            <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.material} />
          </group>
          <group name="Circle292_364" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle293_365" position={[-0.931, -1.05, 0.166]} rotation={[1.745, 0, 0]} scale={0.643} />
          <group name="Sphere097_366" position={[-0.898, -1.089, 0.055]} scale={0.578}>
            <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials.material} />
          </group>
          <group name="Circle295_367" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle296_368" position={[-0.898, -1.089, 0.055]} rotation={[2.094, 0, 0]} scale={0.7} />
          <group name="Sphere098_369" position={[-0.858, -1.12, -0.056]} scale={0.542}>
            <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.material} />
          </group>
          <group name="Circle298_370" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle299_371" position={[-0.858, -1.12, -0.056]} rotation={[2.443, 0, 0]} scale={0.751} />
          <group name="Sphere099_372" position={[-0.813, -1.142, -0.167]} scale={0.511}>
            <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials.material} />
          </group>
          <group name="Circle301_373" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle302_374" position={[-0.813, -1.142, -0.167]} rotation={[2.793, 0, 0]} scale={0.752} />
          <group name="Sphere100_375" position={[-0.762, -1.154, -0.278]} scale={0.483}>
            <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.material} />
          </group>
          <group name="Circle304_376" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle305_377" position={[-0.762, -1.154, -0.278]} rotation={[-2.793, 0, 0]} scale={0.713} />
          <group name="Sphere101_378" position={[-0.707, -1.158, -0.387]} scale={0.487}>
            <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.material} />
          </group>
          <group name="Circle307_379" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle308_380" position={[-0.707, -1.158, -0.387]} rotation={[-2.443, 0, 0]} scale={0.699} />
          <group name="Sphere102_381" position={[-0.647, -1.152, -0.493]} scale={0.44}>
            <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.material} />
          </group>
          <group name="Circle310_382" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle311_383" position={[-0.647, -1.152, -0.493]} rotation={[-2.094, 0, 0]} scale={0.615} />
          <group name="Sphere103_384" position={[-0.583, -1.136, -0.596]} scale={0.422}>
            <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.material} />
          </group>
          <group name="Circle313_385" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle314_386" position={[-0.583, -1.136, -0.596]} rotation={[-1.745, 0, 0]} scale={0.583} />
          <group name="Sphere104_387" position={[-0.515, -1.112, -0.695]} scale={0.382}>
            <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.material} />
          </group>
          <group name="Circle316_388" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle317_389" position={[-0.515, -1.112, -0.695]} rotation={[-1.396, 0, 0]} scale={0.532} />
          <group name="Sphere105_390" position={[-0.445, -1.078, -0.788]} scale={0.351}>
            <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials.material} />
          </group>
          <group name="Circle319_391" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle320_392" position={[-0.445, -1.078, -0.788]} rotation={[-Math.PI / 3, 0, 0]} scale={0.5} />
          <group name="Sphere106_393" position={[-0.372, -1.036, -0.877]} scale={0.328}>
            <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials.material} />
          </group>
          <group name="Circle322_394" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle323_395" position={[-0.372, -1.036, -0.877]} rotation={[-0.698, 0, 0]} scale={0.48} />
          <group name="Sphere107_396" position={[-0.297, -0.985, -0.959]} scale={0.313}>
            <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials.material} />
          </group>
          <group name="Circle325_397" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle326_398" position={[-0.297, -0.985, -0.959]} rotation={[-Math.PI / 9, 0, 0]} scale={0.468} />
          <group name="Sphere108_399" position={[-0.22, -0.927, -1.034]} scale={0.308}>
            <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials.material} />
          </group>
          <group name="Circle328_400" position={[-0.007, -0.001, 0.004]} scale={0.7} />
          <group name="Circle329_401" position={[-0.22, -0.927, -1.034]} scale={0.464} />
          <group name="Sphere109_402" position={[0.957, -0.573, 0.853]} scale={0.7}>
            <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.material} />
          </group>
          <group name="Circle332_403" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle333_404" position={[0.957, -0.573, 0.853]} scale={0.7} />
          <group name="Sphere110_405" position={[0.929, -0.488, 0.936]} scale={0.7}>
            <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials.material} />
          </group>
          <group name="Circle335_406" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle336_407" position={[0.929, -0.488, 0.936]} rotation={[Math.PI / 9, 0, 0]} scale={0.7} />
          <group name="Sphere111_408" position={[0.894, -0.398, 1.011]} scale={0.7}>
            <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials.material} />
          </group>
          <group name="Circle338_409" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle339_410" position={[0.894, -0.398, 1.011]} rotation={[0.698, 0, 0]} scale={0.7} />
          <group name="Sphere112_411" position={[0.854, -0.304, 1.078]} scale={0.7}>
            <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials.material} />
          </group>
          <group name="Circle341_412" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle342_413" position={[0.854, -0.304, 1.078]} rotation={[Math.PI / 3, 0, 0]} scale={0.7} />
          <group name="Sphere113_414" position={[0.807, -0.208, 1.137]} scale={0.7}>
            <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials.material} />
          </group>
          <group name="Circle344_415" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle345_416" position={[0.807, -0.208, 1.137]} rotation={[1.396, 0, 0]} scale={0.7} />
          <group name="Sphere114_417" position={[0.756, -0.109, 1.187]} scale={0.643}>
            <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials.material} />
          </group>
          <group name="Circle347_418" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle348_419" position={[0.756, -0.109, 1.187]} rotation={[1.745, 0, 0]} scale={0.643} />
          <group name="Sphere115_420" position={[0.699, -0.009, 1.228]} scale={0.578}>
            <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials.material} />
          </group>
          <group name="Circle350_421" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle351_422" position={[0.699, -0.009, 1.228]} rotation={[2.094, 0, 0]} scale={0.7} />
          <group name="Sphere116_423" position={[0.637, 0.092, 1.259]} scale={0.542}>
            <mesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials.material} />
          </group>
          <group name="Circle353_424" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle354_425" position={[0.637, 0.092, 1.259]} rotation={[2.443, 0, 0]} scale={0.751} />
          <group name="Sphere117_426" position={[0.572, 0.193, 1.28]} scale={0.511}>
            <mesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials.material} />
          </group>
          <group name="Circle356_427" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle357_428" position={[0.572, 0.193, 1.28]} rotation={[2.793, 0, 0]} scale={0.752} />
          <group name="Sphere118_429" position={[0.503, 0.293, 1.291]} scale={0.483}>
            <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials.material} />
          </group>
          <group name="Circle359_430" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle360_431" position={[0.503, 0.293, 1.291]} rotation={[-2.793, 0, 0]} scale={0.713} />
          <group name="Sphere119_432" position={[0.43, 0.391, 1.292]} scale={0.487}>
            <mesh name="Object_476" geometry={nodes.Object_476.geometry} material={materials.material} />
          </group>
          <group name="Circle362_433" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle363_434" position={[0.43, 0.391, 1.292]} rotation={[-2.443, 0, 0]} scale={0.699} />
          <group name="Sphere120_435" position={[0.356, 0.487, 1.283]} scale={0.44}>
            <mesh name="Object_480" geometry={nodes.Object_480.geometry} material={materials.material} />
          </group>
          <group name="Circle365_436" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle366_437" position={[0.356, 0.487, 1.283]} rotation={[-2.094, 0, 0]} scale={0.615} />
          <group name="Sphere121_438" position={[0.279, 0.581, 1.264]} scale={0.422}>
            <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials.material} />
          </group>
          <group name="Circle368_439" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle369_440" position={[0.279, 0.581, 1.264]} rotation={[-1.745, 0, 0]} scale={0.583} />
          <group name="Sphere122_441" position={[0.201, 0.67, 1.236]} scale={0.382}>
            <mesh name="Object_488" geometry={nodes.Object_488.geometry} material={materials.material} />
          </group>
          <group name="Circle371_442" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle372_443" position={[0.201, 0.67, 1.236]} rotation={[-1.396, 0, 0]} scale={0.532} />
          <group name="Sphere123_444" position={[0.122, 0.755, 1.197]} scale={0.351}>
            <mesh name="Object_492" geometry={nodes.Object_492.geometry} material={materials.material} />
          </group>
          <group name="Circle374_445" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle375_446" position={[0.122, 0.755, 1.197]} rotation={[-Math.PI / 3, 0, 0]} scale={0.5} />
          <group name="Sphere124_447" position={[0.042, 0.834, 1.149]} scale={0.328}>
            <mesh name="Object_496" geometry={nodes.Object_496.geometry} material={materials.material} />
          </group>
          <group name="Circle377_448" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle378_449" position={[0.042, 0.834, 1.149]} rotation={[-0.698, 0, 0]} scale={0.48} />
          <group name="Sphere125_450" position={[-0.036, 0.908, 1.092]} scale={0.313}>
            <mesh name="Object_500" geometry={nodes.Object_500.geometry} material={materials.material} />
          </group>
          <group name="Circle380_451" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle381_452" position={[-0.036, 0.908, 1.092]} rotation={[-Math.PI / 9, 0, 0]} scale={0.468} />
          <group name="Sphere126_453" position={[-0.114, 0.976, 1.027]} scale={0.308}>
            <mesh name="Object_504" geometry={nodes.Object_504.geometry} material={materials.material} />
          </group>
          <group name="Circle383_454" position={[-0.011, 0.007, 0.013]} scale={0.7} />
          <group name="Circle384_455" position={[-0.114, 0.976, 1.027]} scale={0.464} />
          <group name="Sphere127_456" position={[1.058, -0.04, -0.916]} scale={0.7}>
            <mesh name="Object_508" geometry={nodes.Object_508.geometry} material={materials.material} />
          </group>
          <group name="Circle387_457" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle388_458" position={[1.058, -0.04, -0.916]} scale={0.7} />
          <group name="Sphere128_459" position={[1.101, -0.136, -0.854]} scale={0.7}>
            <mesh name="Object_512" geometry={nodes.Object_512.geometry} material={materials.material} />
          </group>
          <group name="Circle390_460" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle391_461" position={[1.101, -0.136, -0.854]} rotation={[Math.PI / 9, 0, 0]} scale={0.7} />
          <group name="Sphere129_462" position={[1.137, -0.23, -0.784]} scale={0.7}>
            <mesh name="Object_516" geometry={nodes.Object_516.geometry} material={materials.material} />
          </group>
          <group name="Circle393_463" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle394_464" position={[1.137, -0.23, -0.784]} rotation={[0.698, 0, 0]} scale={0.7} />
          <group name="Sphere130_465" position={[1.164, -0.322, -0.709]} scale={0.7}>
            <mesh name="Object_520" geometry={nodes.Object_520.geometry} material={materials.material} />
          </group>
          <group name="Circle396_466" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle397_467" position={[1.164, -0.322, -0.709]} rotation={[Math.PI / 3, 0, 0]} scale={0.7} />
          <group name="Sphere131_468" position={[1.183, -0.41, -0.627]} scale={0.7}>
            <mesh name="Object_524" geometry={nodes.Object_524.geometry} material={materials.material} />
          </group>
          <group name="Circle399_469" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle400_470" position={[1.183, -0.41, -0.627]} rotation={[1.396, 0, 0]} scale={0.7} />
          <group name="Sphere132_471" position={[1.194, -0.495, -0.54]} scale={0.643}>
            <mesh name="Object_528" geometry={nodes.Object_528.geometry} material={materials.material} />
          </group>
          <group name="Circle402_472" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle403_473" position={[1.194, -0.495, -0.54]} rotation={[1.745, 0, 0]} scale={0.643} />
          <group name="Sphere133_474" position={[1.196, -0.576, -0.448]} scale={0.578}>
            <mesh name="Object_532" geometry={nodes.Object_532.geometry} material={materials.material} />
          </group>
          <group name="Circle405_475" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle406_476" position={[1.196, -0.576, -0.448]} rotation={[2.094, 0, 0]} scale={0.7} />
          <group name="Sphere134_477" position={[1.19, -0.651, -0.352]} scale={0.542}>
            <mesh name="Object_536" geometry={nodes.Object_536.geometry} material={materials.material} />
          </group>
          <group name="Circle408_478" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle409_479" position={[1.19, -0.651, -0.352]} rotation={[2.443, 0, 0]} scale={0.751} />
          <group name="Sphere135_480" position={[1.175, -0.721, -0.253]} scale={0.511}>
            <mesh name="Object_540" geometry={nodes.Object_540.geometry} material={materials.material} />
          </group>
          <group name="Circle411_481" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle412_482" position={[1.175, -0.721, -0.253]} rotation={[2.793, 0, 0]} scale={0.752} />
          <group name="Sphere136_483" position={[1.151, -0.785, -0.151]} scale={0.483}>
            <mesh name="Object_544" geometry={nodes.Object_544.geometry} material={materials.material} />
          </group>
          <group name="Circle414_484" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle415_485" position={[1.151, -0.785, -0.151]} rotation={[-2.793, 0, 0]} scale={0.713} />
          <group name="Sphere137_486" position={[1.12, -0.842, -0.048]} scale={0.487}>
            <mesh name="Object_548" geometry={nodes.Object_548.geometry} material={materials.material} />
          </group>
          <group name="Circle417_487" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle418_488" position={[1.12, -0.842, -0.048]} rotation={[-2.443, 0, 0]} scale={0.699} />
          <group name="Sphere138_489" position={[1.081, -0.892, 0.056]} scale={0.44}>
            <mesh name="Object_552" geometry={nodes.Object_552.geometry} material={materials.material} />
          </group>
          <group name="Circle420_490" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle421_491" position={[1.081, -0.892, 0.056]} rotation={[-2.094, 0, 0]} scale={0.615} />
          <group name="Sphere139_492" position={[1.034, -0.935, 0.16]} scale={0.422}>
            <mesh name="Object_556" geometry={nodes.Object_556.geometry} material={materials.material} />
          </group>
          <group name="Circle423_493" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle424_494" position={[1.034, -0.935, 0.16]} rotation={[-1.745, 0, 0]} scale={0.583} />
          <group name="Sphere140_495" position={[0.98, -0.97, 0.264]} scale={0.382}>
            <mesh name="Object_560" geometry={nodes.Object_560.geometry} material={materials.material} />
          </group>
          <group name="Circle426_496" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle427_497" position={[0.98, -0.97, 0.264]} rotation={[-1.396, 0, 0]} scale={0.532} />
          <group name="Sphere141_498" position={[0.919, -0.997, 0.366]} scale={0.351}>
            <mesh name="Object_564" geometry={nodes.Object_564.geometry} material={materials.material} />
          </group>
          <group name="Circle429_499" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle430_500" position={[0.919, -0.997, 0.366]} rotation={[-Math.PI / 3, 0, 0]} scale={0.5} />
          <group name="Sphere142_501" position={[0.851, -1.015, 0.466]} scale={0.328}>
            <mesh name="Object_568" geometry={nodes.Object_568.geometry} material={materials.material} />
          </group>
          <group name="Circle432_502" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle433_503" position={[0.851, -1.015, 0.466]} rotation={[-0.698, 0, 0]} scale={0.48} />
          <group name="Sphere143_504" position={[0.778, -1.026, 0.564]} scale={0.313}>
            <mesh name="Object_572" geometry={nodes.Object_572.geometry} material={materials.material} />
          </group>
          <group name="Circle435_505" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle436_506" position={[0.778, -1.026, 0.564]} rotation={[-Math.PI / 9, 0, 0]} scale={0.468} />
          <group name="Sphere144_507" position={[0.699, -1.028, 0.657]} scale={0.308}>
            <mesh name="Object_576" geometry={nodes.Object_576.geometry} material={materials.material} />
          </group>
          <group name="Circle438_508" position={[-0.007, -0.001, 0.003]} scale={0.7} />
          <group name="Circle439_509" position={[0.699, -1.028, 0.657]} scale={0.464} />
        </group>
        <mesh name="Object_580" geometry={nodes.Object_580.geometry} material={materials.material_1} position={[-0.008, 0.007, 0.005]} scale={0.1} />
        <mesh name="Object_582" geometry={nodes.Object_582.geometry} material={materials.material_2} position={[-0.008, 0.007, 0.005]} scale={2.43} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/dragon/scene-transformed.glb')
